#!/bin/bash

# The whole stashing dance based on: http://stackoverflow.com/a/20480591/1435658

# First, stash index and work dir, keeping only the
# to-be-committed changes in the working directory.
# Will also stash uncommitted files
old_stash=$(git rev-parse --quiet --verify refs/stash)
git stash push --quiet --include-untracked --keep-index
new_stash=$(git rev-parse --quiet --verify refs/stash)

# Skip if nothing was stashed
if [ "$old_stash" = "$new_stash" ]; then
	exit 0
fi

# Restore the stash after the tests are run
restore() {
	git reset --hard --quiet && git stash pop --index --quiet
}
trap restore EXIT

npm run format:check || exit 1
npm run lint || exit 1
npm run test || exit 1
npm run build || exit 1
