version = 1

[[annotations]]
# We don't consider the top level configuration files copyrightable in any way
path = [
	".*",
	"package*.json",
	"tsconfig.*",
	"config.dev.json",
	"eslint.config.mjs",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
