/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BattleStartResponse {
	/**
	 * @minItems 1
	 */
	ips: [string | string, ...(string | string)[]];
	port: number;
	[k: string]: unknown;
}
