/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateEvent {
	battleId: string;
	/**
	 * Unix timestamp in microseconds
	 */
	time: number;
	update:
		| StartUpdate
		| FinishedUpdate
		| EngineMessageUpdate
		| EngineWarningUpdate
		| EngineQuitUpdate
		| EngineCrashUpdate
		| PlayerJoinedUpdate
		| PlayerLeftUpdate
		| PlayerChatUpdate
		| PlayerDefeatedUpdate
		| LuaMsgUpdate;
}
/**
 * The battle started.
 */
export interface StartUpdate {
	type: 'start';
}
/**
 * The battle finished, generated once per every single player reporting who won.
 */
export interface FinishedUpdate {
	type: 'finished';
	userId: string;
	/**
	 * @minItems 1
	 */
	winningAllyTeams: [number, ...number[]];
}
/**
 * A message from the engine, e.g. some ip is trying to connect.
 */
export interface EngineMessageUpdate {
	type: 'engine_message';
	message: string;
}
export interface EngineWarningUpdate {
	type: 'engine_warning';
	message: string;
}
/**
 * The engine process for battle has quit cleanly, no more updates will be sent for this battle.
 */
export interface EngineQuitUpdate {
	type: 'engine_quit';
}
/**
 * The engine process for battle has crashed, no more updates will be sent for this battle.
 */
export interface EngineCrashUpdate {
	type: 'engine_crash';
}
export interface PlayerJoinedUpdate {
	type: 'player_joined';
	userId: string;
	/**
	 * Player number in the game, can be useful for custom commands
	 */
	playerNumber: number;
}
export interface PlayerLeftUpdate {
	type: 'player_left';
	userId: string;
	reason: 'lost_connection' | 'left' | 'kicked';
}
export interface PlayerChatUpdate {
	type: 'player_chat';
	userId: string;
	message: string;
	destination: 'allies' | 'all' | 'spectators' | 'player';
	toUserId?: string;
}
export interface PlayerDefeatedUpdate {
	type: 'player_defeated';
	userId: string;
}
export interface LuaMsgUpdate {
	type: 'luamsg';
	userId: string;
	script: 'ui' | 'gaia' | 'rules';
	uiMode?: 'all' | 'allies' | 'spectators';
	data: string;
}
